# Generated by Django 4.1.3 on 2022-12-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLOL', '0002_personajes'),
    ]

    operations = [
        migrations.CreateModel(
            name='comunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=20)),
                ('runas', models.CharField(max_length=100)),
                ('build', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='nuevoitem',
            new_name='items',
        ),
    ]
