# Generated by Django 4.1.3 on 2022-12-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLOL', '0003_comunity_rename_nuevoitem_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunity',
            old_name='items',
            new_name='campeon',
        ),
    ]
