# Generated by Django 4.1.3 on 2022-12-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLOL', '0006_alter_items_cualidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='precio',
            field=models.CharField(max_length=40),
        ),
    ]
